### ISSUE TITLE
untrusted host  in docker

### ISSUE THREAD

**Issue by npnpatidar** [brunostjohn/perplexideez#1]
when i run the docker compose I am getting  in perplexideez container: 

Error: There was a problem with the server configuration. Check the server logs for more information.

    at auth (file:///app/build/server/chunks/auth-Bjq7aU_V.js:6881:9)

    at async file:///app/build/server/chunks/hooks.server-BbPuiw3z.js:4409:21

    at async respond (file:///app/build/server/index.js:3789:22)

    at async Array.ssr (file:///app/build/handler.js:1270:3)

UntrustedHost: Host must be trusted. URL was: https://test.example.com/auth/session. Read more at https://errors.authjs.dev#untrustedhost

    at assertConfig (file:///app/build/server/chunks/auth-Bjq7aU_V.js:395:12)

    at Auth (file:///app/build/server/chunks/auth-Bjq7aU_V.js:6735:27)

    at async auth (file:///app/build/server/chunks/auth-Bjq7aU_V.js:6869:20)

    at async file:///app/build/server/chunks/hooks.server-BbPuiw3z.js:4409:21 {

  type: 'UntrustedHost',

  kind: 'error'

}

## Other information:

I have  updated .env file as below

PUBLIC_BASE_URL="https://test.example.com"

AUTH_SECRET="GMCP/KxpI6o6A2VMDpkppwbKAy1KueURSF/FIoRiAB4="

AUTH_TRUST_HOST="true"

OIDC_CLIENT_ID="perplexideez"
OIDC_CLIENT_SECRET="clientSecret"
OIDC_ISSUER="https://sso.example.com/.well-known/openid-configuration"
OIDC_SCOPES="openid email profile"
PUBLIC_OIDC_NAME="Authelia"

I have authelia for sso and using nginx as reverse proxy.  all containers are running healthy.

**Comment by brunostjohn** [comment]
Hi.

Thanks for reporting an issue! Please give me some time to try to reproduce this issue and get back to you. Thanks!

**Comment by brunostjohn** [comment]
Hi!

Just dropped the 1.0.0 version. Once both Docker images build, your issue should be fixed. Please consult the readme for more info on how to set up the app fully.

Thanks!
