### ISSUE TITLE
Environmental Variables for Postgres User\Pass\DB

### ISSUE THREAD

**Issue by j0nathanr** [brunostjohn/perplexideez#3]
As of now the docker image uses "postgres" for the username, password and database for the postgres DB without any way of changing it with environmental variables

Ideally, we should have a way of setting these credentials with environmental variables in order to further secure the instance

**Comment by brunostjohn** [comment]
You can change the Docker environment variables for the database itself (to make it initialise with different credentials) and for the app (to correctly use these credentials). Support with database sysadmin is out of scope for this project, the app itself supports any user/password/database name combo out there.
