### ISSUE TITLE
Server error - unauthenticated user redirected to /auth

### ISSUE THREAD

**Issue by fahdmirza** [brunostjohn/perplexideez#6]
Hi,
   I am trying to install it locally by following the read me and getting following error :

(ai) Ubuntu@0056-kci-prxmx10054:~/perplexideez$ pnpm dev

> perplexideez@0.0.1 dev /home/Ubuntu/perplexideez
> vite dev

  VITE v5.4.10  ready in 1456 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
INFO [00:47:51.928] (258221): Connected to database
INFO [00:47:52.856] (258221): Starting metrics server
    port: 9001
WARN [00:47:53.088] (258221): debug-enabled
TRACE [00:47:53.095] (258221): unauthenticated user redirected to /auth
    pathname: "/"
ERROR [00:48:18.487] (258221): Error in auth
    err: {
      "type": "TypeError",
      "message": "fetch failed: get

Following are the steps I have followed. My Ollama is already running on local host at default URL and  port:

conda create -n ai python=3.11 -y && conda activate ai

git clone https://github.com/brunostjohn/perplexideez.git && cd perplexideez

pnpm --version 

pnpm install

cp .env.example .env 

pnpm dev:up

and then in other terminal:

pnpm db:push

pnpm dev

and in browser, when I type http://localhost:5173/
it asks me to sign in and gives Server Error.

Do I need to change anything in .env file? Can I also request you to make Read Me, and installation instructions easier to follow for local? Thanks

**Comment by brunostjohn** [comment]
I'm sorry, but there's no support for bare metal deployments.
As per the readme:

> Due to a lack of control over these environments and high variance between them, deploying without using container images is unsupported and such issues will go closed due to being out of scope.

**Comment by fahdmirza** [comment]
Would be good to remove that part from your Readme then.

**Comment by brunostjohn** [comment]
The part of the read me you're referring to is one describing rudimentary steps to prepare the development environment for someone looking to contribute to this project. It assumes the user has some knowledge of web development stacks and other technologies. The part for end user deployment clearly states bare metal deployments are unsupported. Thanks.
