### ISSUE TITLE
dependency failed to start: container docker-searxng-1 is unhealthy

### ISSUE THREAD

**Issue by fahdmirza** [brunostjohn/perplexideez#7]
Hi,
 Trying to install it with docker and getting following error. Also have copied .env file to the /deploy/docker directory. 

(ai) Ubuntu@0056-kci-prxmx10054:~/perplexideez/deploy/docker$ docker --version
Docker version 27.3.1, build ce12230

(ai) Ubuntu@0056-kci-prxmx10054:~/perplexideez/deploy/docker$ docker compose up -d
[+] Running 52/7
 ✔ ollama Pulled                                                                                        86.2s 
 ✔ postgres Pulled                                                                                      13.2s 
 ✔ migrate_db Pulled                                                                                    11.8s 
 ✔ redis Pulled                                                                                          5.5s 
 ✔ perplexideez Pulled                                                                                  27.2s 
 ✔ searxng Pulled                                                                                       14.3s 
 ✔ init_db Pulled                                                                                       13.2s 
[+] Running 11/11
 ✔ Network docker_default           Created                                                              0.2s 
 ✔ Volume "docker_ollama-data"      Created                                                              0.0s 
 ✔ Volume "docker_pgdata"           Created                                                              0.0s 
 ✔ Volume "docker_valkey-data"      Created                                                              0.0s 
 ✔ Container docker-redis-1         Healthy                                                              9.0s 
 ✔ Container docker-ollama-1        Healthy                                                              9.8s 
 ✔ Container docker-init_db-1       Exited                                                               3.9s 
 ✔ Container docker-postgres-1      Healthy                                                              7.0s 
 ✘ Container docker-searxng-1       Error                                                                7.1s 
 ✔ Container docker-perplexideez-1  Created                                                              0.0s 
 ✔ Container docker-migrate_db-1    Started                                                              7.4s 
dependency failed to start: container docker-searxng-1 is unhealthy

**Comment by brunostjohn** [comment]
Problems not related directly to the app's 2 containers (migrate_db and app) are also not supported. Please refer to Redis logs & issues for support.

**Comment by fahdmirza** [comment]
You are too quick to dismiss issues and close the tickets. Documentation is not helpful, project is half-baked, and seems like a complete waste of time.

**Comment by brunostjohn** [comment]
I dismiss issues as I deem appropriate, it's my decision. I dismissed your issue because your SearXNG configuration is most likely messed up (you NEED to change the SearXNG key in the .env) file and you didn't even provide logs from the start. I assume a user has some sort of proficiency with deploying containers because it isn't my dream to be someone's tech support in my free time. I'm here to fix issues with my code, and my code only. Good luck!

**Comment by fahdmirza** [comment]
Then keep this project in your cupboard and not for public consumption. With this arrogance and low-quality project, you are just wasting people's time. The interesting part is that you haven't even created anything original but a clone and a terrible one which doesnt even work. I will stop wasting more time on this useless discussion.
